services:
  ms:
    image: metasploitframework/metasploit-framework:latest
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    depends_on:
      - db
    network_mode: "host"
    ports:
      - "4444:4444"

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: "host"
